[workspace]
members = ["test-suite"]

[package]
name = "crossfire"
version = "3.1.8"
authors = ["plan <frostyplanet@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://github.com/frostyplanet/crossfire-rs"
readme = "README.md"
repository = "https://github.com/frostyplanet/crossfire-rs"
documentation = "https://docs.rs/crossfire"
keywords = ["async", "non-blocking", "lock-free", "channel"]
categories = ["concurrency", "data-structures"]
exclude = ["/ci/*", "/bors.toml"]
description = "channels for async and threads"
rust-version = "1.79"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Because cargo-show-asm cannot match local crossfire package
#[patch.crates-io]
#crossfire = { path = "." }

[dependencies]
crossbeam-utils = "0.8"
futures-core = "0.3"
parking_lot = "0"
tokio = { version = "1", features = ["time", "rt"], optional=true }
async-std = {version = "1", optional=true}
log = { version="0", optional=true}
smallvec = "1"

[dev-dependencies]
log = "0"
tokio = { version = "1", features = ["time", "sync", "rt-multi-thread", "rt", "macros"] }
smol = "2"
captains-log = "0"

## For profiling symbol
#[profile.release]
#debug = true

[features]
default = []

# Enable compat model for v2.x API
compat = []

# This will enable timeout function
tokio = ["dep:tokio"]

# This will enable timeout function
async_std = ["dep:async-std"]

# for test workflow debugging
trace_log = ["dep:log"]

[package.metadata.docs.rs]
all-features = true
# enable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[lints.clippy]
new_ret_no_self = "allow"
needless_range_loop = "allow"
type_complexity = "allow"
needless_return = "allow"
mut_from_ref = "allow"
transmute_ptr_to_ref = "allow"
len_without_is_empty = "allow"
new_without_default = "allow"
result_unit_err = "allow"
