name: cron-master-compio-arm

on:
  schedule: [cron: "0 */5 * * *"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: "macos-15"

    steps:
    - uses: actions/checkout@v2

      # We use cargo-nextest because cargo test does not forward cancellation signal
    - uses: taiki-e/install-action@nextest

    - name: Run tests with compio multi-thread
      run: WORKFLOW=1 make test_compio

    - name: Run tests with compio multi-thread --release with trace log
      run: WORKFLOW=1 make test_log_compio_release

    - name: Run tests with compio multi-thread --release
      run: WORKFLOW=1 make test_log_release

    - name: Run tests with compio single-thread
      run: WORKFLOW=1 SINGLE_THREAD_RUNTIME=1 make test_compio

    - name: Run tests with compio single-thread --release with trace log
      run: WORKFLOW=1 SINGLE_THREAD_RUNTIME=1 make test_log_compio_release

    - name: Run tests with compio single-thread --release
      run: WORKFLOW=1 SINGLE_THREAD_RUNTIME=1 make test_log_release

    - name: Dump log on cancel
      if: ${{ cancelled() }}
      uses: actions/upload-artifact@v4
      with:
          name: crossfire_ring
          path: /tmp/crossfire_ring.log
