name: leak-dev

on:
  schedule: [cron: "30 */10 * * *"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          ref: dev

    - name: Build
      run: cargo build --verbose

    - name: Run test-suite with LSAN
      run: env WORKFLOW=1 make test_leak

    - name: Run internal test
      run: make test_internal
