name: miri-tokio-log

on:
  workflow_dispatch:
  schedule: [cron: "10 */7 * * *"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install miri
      run:  rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri

    - name: Run miri tests with log (tokio multi thread)
      run: cd test-suite; WORKFLOW=1 scripts/miri.sh --features trace_log,tokio

    - name: collect log
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
          name: crossfire_miri_tokio_multithread
          path: /tmp/crossfire_miri.log
