name: miri-tokio-cur

on:
  workflow_dispatch:
  schedule: [cron: "50 */7 * * *"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install miri
      run:  rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri

    - name: Run miri tests without log (tokio current thread)
      run: cd test-suite; WORKFLOW=1 SINGLE_THREAD_RUNTIME=1 scripts/miri.sh
